/**
 * AUTOGENERATED CONFIGURATION FILE
 * LM35 Temperature Sensor + Cortex-M GPIO Interface
 * Board: STM32F4
 * CPU: Cortex-M4
 * Generated: 2024-12-15T10:30:00.000000
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit config/project_config.json and regenerate
 */

#ifndef __CONFIG_H
#define __CONFIG_H

#include <stdint.h>
#include <stdbool.h>

// Pin Definitions
#define LM35_ADC_PIN            GPIO_PIN_0
#define LM35_ADC_CHANNEL        0
#define STATUS_LED_PIN          GPIO_PIN_13
#define DEBUG_UART_TX_PIN       GPIO_PIN_2
#define DEBUG_UART_RX_PIN       GPIO_PIN_3

// ADC Configuration
#define ADC_RESOLUTION_BITS     12
#define ADC_MAX_VALUE           4095
#define ADC_REF_VOLTAGE         3.3f
#define ADC_SAMPLING_TIME       480
#define ADC_OVERSAMPLING        16
#define ADC_VOLTAGE_PER_STEP    0.000806f
#define ADC_MV_PER_STEP         0.8057f
#define ADC_SAMPLING_RATE_HZ    1000

// UART Configuration
#define DEBUG_UART_ENABLED      1
#define DEBUG_UART_BAUDRATE     115200
#define DEBUG_UART_PORT         USART2

// Sensor Calibration
#define LM35_SENSITIVITY_MV_C   10.0f
#define C_PER_ADC_STEP          0.0806f
#define CALIBRATION_OFFSET      0.0f
#define CALIBRATION_GAIN        1.0f
#define ROOM_TEMP_CALIBRATION   25.0f
#define AUTO_CALIBRATION        1

// Sampling Configuration
#define TEMP_SAMPLE_COUNT       16
#define TEMP_UPDATE_RATE_MS     1000
#define FILTER_ALPHA            0.1f
#define OVERSAMPLING_FACTOR     4

// Temperature Thresholds (Celsius)
#define TEMP_LOW_THRESHOLD      0.0f
#define TEMP_HIGH_THRESHOLD     50.0f
#define TEMP_CRITICAL_THRESHOLD 80.0f

// Conversion Macros
#define ADC_TO_VOLTAGE(adc_val)     ((adc_val) * ADC_VOLTAGE_PER_STEP)
#define ADC_TO_MILLIVOLTS(adc_val)  ((adc_val) * ADC_MV_PER_STEP)
#define ADC_TO_CELSIUS(adc_val)     (((adc_val) * C_PER_ADC_STEP * CALIBRATION_GAIN) + CALIBRATION_OFFSET)
#define MILLIVOLTS_TO_CELSIUS(mv)   (((mv) / LM35_SENSITIVITY_MV_C) * CALIBRATION_GAIN + CALIBRATION_OFFSET)
#define CELSIUS_TO_FAHRENHEIT(c)    ((c) * 9.0f / 5.0f + 32.0f)
#define FAHRENHEIT_TO_CELSIUS(f)    (((f) - 32.0f) * 5.0f / 9.0f)

// Status Codes
typedef enum {
    TEMP_READ_SUCCESS = 0,
    TEMP_READ_ERROR_ADC,
    TEMP_READ_ERROR_OVERRANGE,
    TEMP_READ_ERROR_UNDERRANGE,
    TEMP_READ_ERROR_TIMEOUT
} TempReadStatus;

// Temperature Status
typedef enum {
    TEMP_STATUS_NORMAL = 0,
    TEMP_STATUS_LOW,
    TEMP_STATUS_HIGH,
    TEMP_STATUS_CRITICAL,
    TEMP_STATUS_ERROR
} TemperatureStatus;

// Filter Types
typedef enum {
    FILTER_NONE = 0,
    FILTER_MOVING_AVERAGE,
    FILTER_EXPONENTIAL,
    FILTER_MEDIAN
} FilterType;

// Board Information
#define BOARD_TYPE              "STM32F4"
#define BOARD_CPU               "Cortex-M4"
#define BOARD_CLOCK_HZ          168000000UL
#define FIRMWARE_VERSION        "1.0.0"

// Function Prototypes
float read_temperature_celsius(void);
float read_temperature_fahrenheit(void);
TemperatureStatus get_temperature_status(float temperature_c);
void calibrate_temperature_sensor(float reference_temp_c);
void update_calibration_parameters(float offset, float gain);

// Debug Macros
#ifdef DEBUG_ENABLED
    #define DEBUG_PRINT(fmt, ...)   debug_printf(fmt, ##__VA_ARGS__)
    #define DEBUG_HEX(data, len)    debug_print_hex(data, len)
#else
    #define DEBUG_PRINT(fmt, ...)   ((void)0)
    #define DEBUG_HEX(data, len)    ((void)0)
#endif

#endif // __CONFIG_H
